services:
  #postgreSQL Database
  data-base:
    image: pgvector/pgvector:pg15
    container_name: galaxy-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'galaxyarchive'
      POSTGRES_USER: 'galaxyarchive'
      POSTGRES_PASSWORD: '@wu98061612'
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - galaxy-network

  #Kafka
  Kafka:
    image: apache/kafka:latest
    container_name: galaxy-kafka
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'

      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://galaxy-kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=galaxy-kafka -Dcom.sun.management.jmxremote.rmi.port=9997"

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFLINE_IMAGE_MODE: 'true'
    networks:
      - galaxy-network
  Kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: galaxy-kafka-ui

    #kafak dash board url entiry point
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: galaxy-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: galaxy-kafka:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - galaxy-network

  #AI Embedding Engine
  ollama:
    image: ollama/ollama:latest
    container_name: galaxy-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./volumes/ollama_data:/root/.ollama

  #minio Object Storage
  minio:
    image: quay.io/minio/minio:latest
    container_name: galaxy-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: 'galaxyarchive'
      MINIO_ROOT_PASSWORD: 'galaxyarchivepw'
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: always
networks:
  galaxy-network:
    driver: bridge