services:
  #postgreSQL Database
  data-base:
    image: pgvector/pgvector:pg15
    container_name: galaxy-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'galaxyarchive'
      POSTGRES_USER: 'galaxyarchive'
      POSTGRES_PASSWORD: '@wu98061612'
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - galaxy-network

  #Kafka
  Kafka:
    image: apache/kafka:latest
    container_name: galaxy-kafka
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'

      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      KAFKA_OFFLINE_IMAGE_MODE: 'true'
    networks:
      - galaxy-network
  Kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: galaxy-kafka-ui

    #kafak dash board url entiry point
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: galaxy-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: Kafka:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - galaxy-network
networks:
  galaxy-network:
    driver: bridge