services:
  data-base:
    image: postgres:15-alpine
    container_name: galaxy-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=galaxyarchive
      - POSTGRES_USER=galaxyarchive
      - POSTGRES_PASSWORD=@wu98061612
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - galaxy-network

networks:
  galaxy-network:
    driver: bridge