logging:
  level:
    com.hyunbindev: DEBUG
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/galaxyarchive
    username: galaxyarchive
    password: '@wu98061612' #${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
  ai:
    ollama:
      base-url: "http://localhost:11434"
      embedding:
        options:
          model: bge-m3

cloud:
  aws:
    credentials:
      access-key: 'galaxyarchive'
      secret-key: 'galaxyarchivepw'
    region:
      static: 'ap-northeast-2'
    s3:
      endpoint: 'http://localhost:9000'
      bucket: 'galaxy-archive'

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
